### ISSUE TITLE
Use appropriate type in generated C# schema files

### ISSUE THREAD

**Issue by rthery** [colyseus/colyseus-unity3d#139]
I've noticed that if I use Colyseus primitive type uint8 for a property in a schema, the generated C# will use uint instead of [byte](https://docs.microsoft.com/en-us/dotnet/api/system.byte?view=netstandard-2.0)

Probably best to go over all the primitive types supported by Colyseus and make sure that the generated C# use the matching ones, cf. https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/integral-numeric-types

**Comment by endel** [comment]
Hi @rthery, thank you for noticing and reporting this! You're right, both `int8` and `uint8` had to be changed to `sbyte` and `byte` respectively. 

I've just released version [`0.14.4` of the unity plugin](https://github.com/colyseus/colyseus-unity3d/releases/tag/0.14.4), and the latest version of `@colyseus/schema` (`1.0.19`) is now generating sbyte/byte instead of int8/uint8.

**Important:** If you happen to upgrade `@colyseus/schema` without upgrading the Unity client to `0.14.4+` (while using int8/uint8) you're going to see a type conversion error, if that happens to you just upgrade the Unity client (This is the breaking change https://github.com/colyseus/colyseus-unity3d/commit/2d54b25c1b8118191a627556d06aa14313f269f8)
