### ISSUE TITLE
release package just what is needed

### ISSUE THREAD

**Issue by Wenish** [colyseus/colyseus-unity3d#92]
It would be nice. If in the github releases there would be a zip with only the relevant files.
Afaik it only needs the plugins folder.
So a developer can just download this folder then the hole source. and search the plugins manually.

im willing to do this. but im not sure how the CI/CD on this project works if there is any?

**Comment by endel** [comment]
Hi @Wenish, I love this idea. There aren't any CI/CD currently on `colyseus-unity3d`. I just searched and it seems this is what we need https://github.com/kevinta893/unity3d-travis-ci

It would be awesome if you make a PR for this! ❤️

**Comment by Wenish** [comment]
@endel what are the things you do atm before release?

**Comment by endel** [comment]
@Wenish I currently check inside the editor if the tests are passing (for simplicity sake, we can skip `TestConnection` for now, since it needs a sample server to be running, we can spawn a server later on I think!)

![Screenshot 2019-10-07 at 08 04 43](https://user-images.githubusercontent.com/130494/66306862-294d7480-e8d9-11e9-8d23-08579809cc2a.png)

**Comment by Wenish** [comment]
@endel is it important for you that the pipeline is on travis?
i tried it multiple times. (i also know the repo you linked) but the problem is there that it lacks the support for downloading the correct unity version. so on every unity update it would need a change in the .travis file with the new download url from unity. or if the download link breaks. (because unity changes it) the pipeline breaks also.

i personally know now how to do this with azure devops, since there is a unity extension which addresses those problems.

for the TestConnection test:
does it only needs a local server?
because imo this should also work pretty straight forward on a build agent

only thing a never tried is to run unity tests from command line but should also be possible:
https://docs.unity3d.com/Packages/com.unity.test-framework@1.1/manual/reference-command-line.html

**Comment by endel** [comment]
Hey @Wenish, if it's easier to set this up on another open-source friendly CI, let's go for it! (I didn't know about this until now 😅 https://azure.microsoft.com/en-us/blog/announcing-azure-pipelines-with-unlimited-ci-cd-minutes-for-open-source/)

> for the TestConnection test:
does it only needs a local server?
because imo this should also work pretty straight forward on a build agent

Yes, only a local server is needed! I mentioned we can postpone this because it can be a whole another thing to set-up (besides having Unity3d + unit tests running, also a NodeJS server). If you wanna do it as well it would be perfect!

Cheers!

**Comment by endel** [comment]
Closing this as the new UPM support should cover this! :) https://github.com/colyseus/colyseus-unity3d/pull/146
